version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9.7-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Set up Python virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install Python dependencies
          command: |
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Linting
          command: |
            flake8 --max-line-length=120 .
      - run:
          name: Pytest
          command: |
            pytest --cov=.
      - run:
          name: Containerize
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker build -t oc_lettings .
            docker tag oc_lettings $DOCKER_LOGIN/oc_lettings
            docker push $DOCKER_LOGIN/oc_lettings
      - run:
          name: Notify Sentry of deployment
          command: |
            curl -X POST \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $SENTRY_AUTH_TOKEN" \
            -d "{\"version\": \"$CIRCLE_SHA1\"}" \
            "https://sentry.io/api/0/projects/openclassrooms-rj/oc_lettings/releases/"

workflows:
  build:
    jobs:
      - build-and-test
